version: "3.7"

# Note: SCX dependency assume Docker images already exist
services:
  mysql:
    build: ./docker/mysql/
    command: --max_allowed_packet=1073741824
    restart: always
    logging:
      driver: none
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: exampledb
    ports:
      - "3306:3306"